# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5692efe1d7dc2e8816b25030bdecfc9cc6c38e6c9bdde8872122d15e24272430b50ffc24acef5d49521dbb66acf84d8db4a518dfbef55b6a16d93ea9689d6b91

test:
  secret_key_base: 7937e76deb4f1b1c85d07982593325fb5ffbc088f08deee411fdd7f4058b3f585a6b2b2455a013fd50bf4f49f81c366a58f73071a56912d707b9e9e742ec167a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
